# GET http://localhost:9000/test

# GET http://localhost:9000/test/match/

# GET http://localhost:9000/test/group/

# GET http://localhost:9000/test/match-group/

# GET http://localhost:9000/test/count/

# GET http://localhost:9000/test/group-count/

# GET http://localhost:9000/test/sort/

# GET http://localhost:9000/test/group-sort/

# GET http://localhost:9000/test/project/

# GET http://localhost:9000/test/limit/

# GET http://localhost:9000/test/limit-match-group/

# GET http://localhost:9000/test/unwind/

# GET http://localhost:9000/test/unwind-group/

# GET http://localhost:9000/test/sum/

# GET http://localhost:9000/test/avg/

# GET http://localhost:9000/test/type/

# GET http://localhost:9000/test/out/

# GET http://localhost:9000/test/allowDiskUse/














